### ISSUE TITLE
Inshellisense with oh-my-bash stops working after the first executed command

### ISSUE THREAD

**Issue by whiskeyo** [microsoft/inshellisense#201]
**Describe the bug**
While entering the first command, the window with suggestion appears. Once I pick any subcommand/flag, it turns off and does not work for the next input. After inshellisense started working with this fix: https://github.com/microsoft/inshellisense/pull/200, it turned out that it worked just for a single command.

**To Reproduce**
1. Install oh-my-bash and latest inshellisense (9907244548ee0a2a5890206cdf060bf1e7b5c065)
2. Write the part of the first command, the window with suggestion appears, select any of these, press enter to call it.
3. Write another command, this time the window does not appear anymore.

**Expected behavior**
Inshellisense should support all commands when the session is live.

**Environment**
 - OS: Windows 11, running Debian in WSL2
 - Output of `is --version`: 0.0.1-rc.9, but running commit 9907244548ee0a2a5890206cdf060bf1e7b5c065
 - Nodejs Version: v18.19.0
 - Shell: bash + oh-my-bash
 - Shell Version: 5.2.15(1)-release (x86_64-pc-linux-gnu)

**Additional context**
I recorded a small sample and uploaded it on YouTube to make it easier to get what's happening, here's the link: https://youtu.be/L30cOTPP14E

**Comment by cpendery** [comment]
For reference, this is what I think is happening:

I have setup hooks to inject the `inshellisense` prompt bytes into the prompt for every case except for when a $PROMPT_COMMAND decides to re-write $PS1 after the `precmd` hook is triggered.

**Comment by cpendery** [comment]
@whiskeyo let me know if you run into any other issues

**Comment by cdevacc1** [comment]
I got the same issue. How did you fixed that @cpendery ?

**Comment by kruzyk** [comment]
Same for me with zsh/omz.

**Comment by cpendery** [comment]
> Same for me with zsh/omz, WSL2 - Ubuntu 24.10. With W11 pwsh and oh-my-posh it works like a charm.

This should be fixed in 0.0.1-rc.17 which I'll be releasing soon. Please let me know if it doesn't work after upgrading and making all the changes recommended by `is doctor`

**Comment by IgorMCesar** [comment]
@cpendery 
Still happening on `0.0.1-rc.18` with oh-my-zsh while using `powerlevel10k`.
After the first command is sent it doesn't show anymore.

**Comment by cpendery** [comment]
> [@cpendery](https://github.com/cpendery) Still happening on `0.0.1-rc.18` with oh-my-zsh while using `powerlevel10k`. After the first command is sent it doesn't show anymore.

Can you paste your `.zshrc` here? It might be the instant prompt from `powerlevel10k` or the ordering of your configs that is causing the issue

**Comment by SoyAlejandroCalixto** [comment]
Same issue but with `oh-my-zsh`. This is my `.zshrc`:

```bash
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=(git zsh-autosuggestions zsh-syntax-highlighting zsh-autopair)
eval "$(zoxide init zsh)"
eval "$(atuin init zsh)"

source $ZSH/oh-my-zsh.sh

ZSH_AUTOSUGGEST_STRATEGY=(history completion)

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

alias vim=nvim
alias rcat=/usr/bin/cat
alias cat=bat
alias rls=/usr/bin/ls
alias ls=lsd

eval "$(fnm env --use-on-cd --shell zsh)"

[[ -f ~/.inshellisense/zsh/init.zsh ]] && source ~/.inshellisense/zsh/init.zsh
```

**Comment by IuriKintschev** [comment]
the same here but in my scenario it is powershell, after the first command the prompt does not appear anymore. I also tried to run the command 'is --verbose' but the .log file is not generated for debugging

node: 22.14.0
pwsh: 7.5.0
is: 0.0.1-rc.20

**Comment by keremnalbant** [comment]
Same happens here @cpendery can you check this again. It stops running after the first command is executed.

MacOS 26 - zsh - powerlevel10k - NerdFont.

```.zshrc
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="powerlevel10k/powerlevel10k"

source $ZSH/oh-my-zsh.sh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

[[ -f ~/.inshellisense/zsh/init.zsh ]] && source ~/.inshellisense/zsh/init.zsh
```
